/**
 * React-specific Agentic Core extensions
 * Adds support for StartWorkerAgents and CheckBuild tools
 */

import { 
    AgenticState, 
    AgenticMessage, 
    ToolCall,
    SystemBlock,
    ResponseSegment,
    executeToolCall as baseExecuteToolCall,
    applyDiffCommand
} from '../Agentic/AgenticCoreLangchain';
import { buildReactApp, parseFilesFromConcatenatedCode } from './ReactBuildManager';
import { callGemini } from '../index.tsx';
import { renderPrompt } from '../Components/PromptRenderer';

// Extended state for React mode
export interface ReactAgenticState extends AgenticState {
    orchestratorPlan?: string;
    workerPrompts?: Array<{
        title: string;
        system_instruction: string;
        user_prompt_template: string;
    }>;
    workersExecuted?: boolean;
    lastBuildResult?: {
        success: boolean;
        errors: string[];
        warnings: string[];
    };
    userRequest?: string;
}

// Global reference to the active React pipeline
let activeReactPipeline: any = null;
let customPromptsReactState: any = null;

// Set the active pipeline reference
export function setActiveReactPipeline(pipeline: any) {
    activeReactPipeline = pipeline;
}

// Set the custom prompts state
export function setCustomPromptsReactState(prompts: any) {
    customPromptsReactState = prompts;
}

/**
 * Execute StartWorkerAgents tool
 */
async function executeStartWorkerAgents(state: ReactAgenticState): Promise<{ result: string; updatedContent?: string }> {
    if (state.workersExecuted) {
        return {
            result: '[SYSTEM_ERROR: Worker agents have already been executed. This tool can only be called once.]'
        };
    }

    if (!activeReactPipeline) {
        return {
            result: '[SYSTEM_ERROR: No active React pipeline found. Cannot start worker agents.]'
        };
    }

    if (!activeReactPipeline.orchestratorPlan || !activeReactPipeline.stages) {
        return {
            result: '[SYSTEM_ERROR: Orchestrator plan or worker prompts not available.]'
        };
    }

    try {
        // Mark workers as starting
        activeReactPipeline.status = 'processing_workers';
        
        // Execute all worker agents in parallel
        const workerPromises = activeReactPipeline.stages.map(async (stage: any) => {
            if (!stage.systemInstruction || !stage.userPrompt) {
                stage.status = 'error';
                stage.error = 'Missing system instruction or user prompt';
                return stage;
            }

            stage.status = 'processing';
            
            // Render the user prompt with the plan
            stage.renderedUserPrompt = renderPrompt(stage.userPrompt, {
                plan_txt: activeReactPipeline.orchestratorPlan || '',
                user_request: activeReactPipeline.userRequest || ''
            });

            try {
                // Call the AI for this worker
                const workerModel = customPromptsReactState?.model_worker || 'gemini-2.0-flash-exp';
                const response = await callGemini(
                    stage.renderedUserPrompt,
                    0.7, // Temperature
                    workerModel,
                    stage.systemInstruction,
                    false // Not expecting JSON
                );

                stage.generatedContent = response.text;
                stage.status = 'completed';
                return stage;
            } catch (error: any) {
                stage.status = 'error';
                stage.error = error.message || 'Worker agent failed';
                return stage;
            }
        });

        // Wait for all workers to complete
        await Promise.allSettled(workerPromises);

        // Aggregate the outputs
        let combinedCode = `/* --- React Application Code --- */\n`;
        combinedCode += `/* Generated by Iterative Studio */\n`;
        combinedCode += `/* User Request: ${activeReactPipeline.userRequest} */\n\n`;
        combinedCode += `/* --- Orchestrator Plan (plan.txt) --- */\n/*\n${activeReactPipeline.orchestratorPlan || 'No plan generated.'}\n*/\n\n`;

        activeReactPipeline.stages.forEach((stage: any, index: number) => {
            if (stage.status === 'completed' && stage.generatedContent) {
                combinedCode += `/* --- File: ${stage.title || `Agent${index + 1}Output`} --- */\n`;
                combinedCode += `${stage.generatedContent.trim()}\n\n`;
            } else if (stage.status === 'error') {
                combinedCode += `/* --- Agent ${index + 1}: ${stage.title} - FAILED --- */\n`;
                combinedCode += `/* Error: ${stage.error || 'Unknown error'} */\n\n`;
            }
        });

        // Mark workers as executed
        (state as any).workersExecuted = true;

        // Return the combined code as the new content
        return {
            result: '[TOOL_RESULT: Worker agents completed. Full application codebase loaded into context.]',
            updatedContent: combinedCode
        };

    } catch (error: any) {
        return {
            result: `[SYSTEM_ERROR: Failed to execute worker agents: ${error.message}]`
        };
    }
}

/**
 * Execute CheckBuild tool
 */
async function executeCheckBuild(state: ReactAgenticState): Promise<{ result: string }> {
    try {
        // Build the current content
        const buildResult = await buildReactApp(state.currentContent);
        
        // Store the build result
        (state as any).lastBuildResult = buildResult;

        if (buildResult.success) {
            let result = '[BUILD_SUCCESS: Application built successfully!]';
            if (buildResult.warnings.length > 0) {
                result += '\n\nWarnings:\n' + buildResult.warnings.join('\n');
            }
            return { result };
        } else {
            let result = '[BUILD_FAILED: Build errors detected]\n\n';
            result += 'Errors:\n' + buildResult.errors.join('\n\n');
            if (buildResult.warnings.length > 0) {
                result += '\n\nWarnings:\n' + buildResult.warnings.join('\n');
            }
            return { result };
        }
    } catch (error: any) {
        return {
            result: `[SYSTEM_ERROR: Build check failed: ${error.message}]`
        };
    }
}

/**
 * Extended tool execution for React mode
 */
export async function executeReactToolCall(
    toolCall: ToolCall,
    state: ReactAgenticState
): Promise<{ 
    result: string; 
    updatedContent?: string;
    isComplete?: boolean;
}> {
    // Handle React-specific tools
    if (toolCall.name === 'StartWorkerAgents') {
        return await executeStartWorkerAgents(state);
    }
    
    if (toolCall.name === 'CheckBuild') {
        return await executeCheckBuild(state);
    }
    
    // Handle Exit tool
    if (toolCall.name === 'Exit') {
        return {
            result: '[Agent exiting. Task completed.]',
            isComplete: true
        };
    }
    
    // For other tools, use the base implementation
    const baseResult = await baseExecuteToolCall(toolCall, state);
    
    // Check if it's a multi_edit and apply the changes
    if (toolCall.name === 'multi_edit' && baseResult.result.includes('successfully applied')) {
        // Parse and apply the diff commands
        const diffCommands = toolCall.params as any;
        if (Array.isArray(diffCommands)) {
            let updatedContent = state.currentContent;
            for (const cmd of diffCommands) {
                const result = applyDiffCommand(cmd, updatedContent);
                if (result.success && result.newContent) {
                    updatedContent = result.newContent;
                }
            }
            return {
                ...baseResult,
                updatedContent
            };
        }
    }
    
    return baseResult;
}

/**
 * Parse React-specific tool calls from agent response
 */
export function parseReactToolCall(text: string): ToolCall | null {
    // Check for StartWorkerAgents
    const startWorkersMatch = text.match(/\[TOOL_CALL:StartWorkerAgents\(\)\]/);
    if (startWorkersMatch) {
        return {
            name: 'StartWorkerAgents',
            params: {}
        };
    }
    
    // Check for CheckBuild
    const checkBuildMatch = text.match(/\[TOOL_CALL:CheckBuild\(\)\]/);
    if (checkBuildMatch) {
        return {
            name: 'CheckBuild',
            params: {}
        };
    }
    
    // Check for Exit
    const exitMatch = text.match(/\[TOOL_CALL:Exit\(\)\]/);
    if (exitMatch) {
        return {
            name: 'Exit',
            params: {}
        };
    }
    
    // For other tools, return null and let the base parser handle it
    return null;
}
