
import { CustomizablePromptsWebsite } from '../Refine/RefinePrompts';
import { CustomizablePromptsReact } from '../React/ReactPrompts';
import { CustomizablePromptsDeepthink } from '../Deepthink/DeepthinkPrompts';
import { CustomizablePromptsAdaptiveDeepthink } from '../AdaptiveDeepthink/AdaptiveDeepthinkPrompt';
import { CustomizablePromptsContextual } from '../Contextual/ContextualPrompts';
import {
    DeepthinkSolutionCritiqueData,
    DeepthinkSubStrategyData,
    DeepthinkHypothesisData,
    DeepthinkRedTeamData,
    DeepthinkPostQualityFilterData,
    DeepthinkMainStrategyData,
    DeepthinkStructuredSolutionPoolAgentData,
    DeepthinkPipelineState
} from '../Deepthink/DeepthinkCore';

export type {
    DeepthinkSolutionCritiqueData,
    DeepthinkSubStrategyData,
    DeepthinkHypothesisData,
    DeepthinkRedTeamData,
    DeepthinkPostQualityFilterData,
    DeepthinkMainStrategyData,
    DeepthinkStructuredSolutionPoolAgentData,
    DeepthinkPipelineState
};

/**
 * Custom error class to signify that pipeline processing was intentionally
 * stopped by a user request.
 */
export class PipelineStopRequestedError extends Error {
    constructor(message: string) {
        super(message);
        this.name = "PipelineStopRequestedError";
    }
}

export type ApplicationMode = 'website' | 'deepthink' | 'react' | 'agentic' | 'generativeui' | 'contextual' | 'adaptive-deepthink';

export interface IterationData {
    iterationNumber: number;
    title: string;
    // Website Mode Specific
    requestPromptContent_InitialGenerate?: string;
    requestPromptContent_FeatureImplement?: string;
    requestPromptContent_BugFix?: string;
    requestPromptFeatures_Suggest?: string;
    generatedContent?: string;
    contentBeforeBugFix?: string; // Content state before bug-fix patches are applied
    suggestedFeaturesContent?: string; // Markdown content from feature suggestion agent

    // Removed diff-format patches - now using full content updates

    status: 'pending' | 'processing' | 'retrying' | 'completed' | 'error' | 'cancelled';
    error?: string;
    isDetailsOpen?: boolean;
    retryAttempt?: number;
}

export interface PipelineState {
    id: number;
    originalTemperatureIndex: number;
    temperature: number;
    modelName: string;
    iterations: IterationData[];
    status: 'idle' | 'running' | 'stopping' | 'stopped' | 'completed' | 'failed';
    tabButtonElement?: HTMLButtonElement;
    contentElement?: HTMLElement;
    stopButtonElement?: HTMLButtonElement;
    isStopRequested?: boolean;
}




// React Mode Specific Interfaces
export interface ReactModeStage { // Exporting for potential use elsewhere, though primarily internal
    id: number; // 0-4 for the 5 worker agents
    title: string; // e.g., "Agent 1: UI Components" - defined by Orchestrator
    systemInstruction?: string; // Generated by Orchestrator for this worker agent
    userPrompt?: string; // Generated by Orchestrator for this worker agent (can be a template)
    renderedUserPrompt?: string; // If the userPrompt is a template
    generatedContent?: string; // Code output from this worker agent
    status: 'pending' | 'processing' | 'retrying' | 'completed' | 'error' | 'cancelled';
    error?: string;
    isDetailsOpen?: boolean;
    retryAttempt?: number;
}

export interface ReactPipelineState { // Exporting for potential use elsewhere
    id: string; // Unique ID for this React mode process run
    userRequest: string;
    orchestratorSystemInstruction: string; // The system prompt used for the orchestrator
    orchestratorPlan?: string; // plan.txt generated by Orchestrator
    orchestratorRawOutput?: string; // Full raw output from orchestrator (for debugging/inspection)
    stages: ReactModeStage[]; // Array of 5 worker agent stages
    finalAppendedCode?: string; // Combined code from all worker agents
    status: 'idle' | 'orchestrating' | 'processing_workers' | 'completed' | 'error' | 'stopping' | 'stopped' | 'cancelled' | 'orchestrating_retrying' | 'failed' | 'agentic_orchestrating';
    error?: string;
    isStopRequested?: boolean;
    activeTabId?: string; // To track which of the 5 worker agent tabs is active in UI, e.g., "worker-0", "worker-1"
    orchestratorRetryAttempt?: number;
    agenticRefineStarted?: boolean; // Embedded Agentic refinement has started inside React mode
    initialAgenticContent?: string; // Initial content for the embedded agentic agent
    workerPromptsData?: any[]; // Worker prompts data for the embedded agent
    workersExecuted?: boolean; // Whether worker agents have been executed
    previewUrl?: string; // Preview URL for the built application
    prevPreviewUrl?: string; // Previous preview URL for cleanup
}

export interface ExportedConfig {
    currentMode: ApplicationMode;
    currentEvolutionMode?: 'off' | 'novelty' | 'quality'; // Evolution convergence mode
    initialIdea: string;
    selectedModel: string;
    selectedOriginalTemperatureIndices: number[]; // For website
    pipelinesState: PipelineState[]; // For website
    activeDeepthinkPipeline?: DeepthinkPipelineState | null; // For deepthink
    activeReactPipeline: ReactPipelineState | null; // Added for React mode
    embeddedAgenticState?: any | null; // For agentic state embedded in React mode
    activeAgenticState?: any | null; // For agentic mode
    activeGenerativeUIState?: any | null; // For generative UI mode
    activeContextualState?: any | null; // For contextual mode
    activeAdaptiveDeepthinkState?: any | null; // For adaptive deepthink mode
    activePipelineId: number | null; // For website
    activeDeepthinkProblemTabId?: string; // For deepthink UI
    globalStatusText: string;
    globalStatusClass: string;
    customPromptsWebsite: CustomizablePromptsWebsite;
    customPromptsDeepthinkState?: CustomizablePromptsDeepthink;
    customPromptsReact: CustomizablePromptsReact; // Added for React mode
    customPromptsAgentic: { systemPrompt: string }; // Added for Agentic mode
    customPromptsAdaptiveDeepthink?: CustomizablePromptsAdaptiveDeepthink; // Added for Adaptive Deepthink mode
    customPromptsContextual?: CustomizablePromptsContextual; // Added for Contextual mode
    isCustomPromptsOpen?: boolean;
    // Model parameters for Deepthink modes
    modelParameters?: {
        temperature: number;
        topP: number;
        refinementStages: number;
        strategiesCount: number;
        subStrategiesCount: number;
        hypothesisCount: number;
        redTeamAggressiveness: string;
        refinementEnabled: boolean;
        skipSubStrategies: boolean;
        dissectedObservationsEnabled: boolean;
        iterativeCorrectionsEnabled: boolean;
        provideAllSolutionsToCorrectors: boolean;
    };
    // Solution pool versions for evolution view
    solutionPoolVersions?: Array<{ content: string; title: string; timestamp: number }> | null;
}
